export const surprisePrompts = [
  "A comical food fight taking place between zombies, playfully hurling brains, eyeballs, and other gory treats at one another",
  "Design a dish that combines ingredients from different planets, resulting in a unique and visually stunning culinary masterpiece",
  "Illustrate a garden party taking place on a floating island among the clouds, attended by celestial beings and mythical creatures",
  "Depict a scene from a classic fairy tale, but set in a futuristic, neon-lit cyberpunk world",
  "A lively band made up of anthropomorphic fruits playing various musical instruments",
  "Envision a microscopic world where nano-bots mimic and interact with natural elements like plants, insects, and weather phenomena",
  "Combine two or more mythical creatures, such as a griffin and a mermaid, to create a unique and fascinating hybrid animal",
  "Design a unique chess set, replacing traditional pieces with intricately detailed animal figures",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "Illustrate a hilarious scene of penguins wearing sunglasses and swimsuits, having a blast at a pool party with tropical drinks and beach balls",
  "Visualize a hacker couple overcoming digital barriers and cyber threats to protect their love",
  "Picture a world where dinosaurs still exist, but they are small and domesticated, becoming lovable pets for humans",
  "Reimagine the classic love story of Romeo and Juliet set in a dystopian, high-tech city",
  "A group of clueless alien tourists, dressed in stereotypical tourist outfits, trying to blend in while sightseeing on Earth",
  "A spooky, atmospheric illustration of a haunted library filled with mysterious books and supernatural occurrences",
  "Illustrate a detective using time-travel technology to solve crimes across different historical periods",
  "A unicorn working as a barista at a trendy coffee shop, using its magical horn to create fantastic latte art",
  "Reimagine the city of Venice with a steampunk twist, featuring canals filled with steam-powered gondolas and intricate mechanical architecture",
  "Create a fantastical realm where dreamcatchers serve as portals to alternate dimensions and mystical landscapes",
  "Create a scene featuring a time-traveling graffiti artist who leaves their mark across different eras",
  "A friendly giant playing with human-sized characters in a whimsical, oversized playground",
  "A funny and vibrant scene where the sun is replaced by a giant disco ball, casting shimmering light and dance-party vibes across the landscape",
  "A resilient character tending to a lush, thriving garden amidst the ruins of a post-apocalyptic world, symbolizing hope and rebirth",
  "A humorous scene of stealthy ninja cats performing acrobatic stunts and engaging in lighthearted combat",
  "Detailed 3D render of ancient alien ruins on a distant planet, revealing mysterious structures and artifacts left behind by an advanced civilization",
];
